# This is a basic workflow to help you get started with Actions

name: build uxplay for windows

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      bonjour_sdk_url:
        description: "Direct URL to BonjourSDKSetup.exe v3.0. Download from https://developer.apple.com/bonjour and upload it somewhere"
        default: ""
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: build uxplay
    # The type of runner that the job will run on
    runs-on: windows-latest    
    permissions:
      contents: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: clone the repo
        uses: actions/checkout@v4

      - name: download Bonjour
        env:
          BONJOUR_URL: ${{ inputs.bonjour_sdk_url }}
        run: Invoke-WebRequest -Uri $env:BONJOUR_URL -OutFile bonjoursdksetup.exe
        
      - name: download & install 7zip
        run: | 
          Invoke-WebRequest -Uri https://7-zip.org/a/7z2301-x64.exe -OutFile 7zip.exe
          .\7zip.exe /S
          Remove-Item 7zip.exe

      - name: extract Bonjour .exe into the .msi(s)
        run: .'C:\Program Files\7-Zip\7z.exe' -tcab x bonjoursdksetup.exe

      # the SDK requires the normal version of Bonjour to be installed first.
      - name: install Bonjour (64 bit)
        run: |
          $currentPath = Get-Location
          $msiFilePath = Join-Path -Path $currentPath -ChildPath "Bonjour64.msi"
          $msiexecArguments = "/i `"$msiFilePath`" /qn /L*v bonjour64.log"
          Start-Process msiexec -ArgumentList $msiexecArguments -NoNewWindow -Wait
      - name: install Bonjour SDK (64 bit)
        run: |
          $msiexecArguments = "/i $(Join-Path -Path $(Get-Location) -ChildPath "BonjourSDK64.msi") /qn /L*v bonjoursdk64.log"
          Start-Process msiexec -ArgumentList $msiexecArguments -NoNewWindow -Wait

      - name: downloading Inno Setup
        run: Invoke-WebRequest https://jrsoftware.org/download.php/is.exe -OutFile is.exe
      - name: installing Inno Setup
        run: start (Join-Path -Path $(Get-Location) -ChildPath "is.exe") /VERYSILENT

      - name: setup msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            zip
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-libplist
            mingw-w64-x86_64-json-glib
            mingw-w64-x86_64-gstreamer
            mingw-w64-x86_64-gst-plugins-base
            mingw-w64-x86_64-gst-libav
            mingw-w64-x86_64-gst-plugins-good
            mingw-w64-x86_64-gst-plugins-bad

      - name: building (finally)
        shell: msys2 {0}
        run: |
          git clone https://github.com/FDH2/UxPlay && cd UxPlay
          mkdir build && cd build
          cmake ..
          ninja
          
          mkdir artifact && cd artifact
          mkdir lib
          cp -r /mingw64/lib/gstreamer-1.0 lib/gstreamer-1.0
          cp -r /mingw64/bin bin
          cp ../uxplay.exe bin
          echo ".\bin\uxplay.exe" > uxplay-windows.bat

      - name: compile the installer with inno setup
        run: .$(Join-Path -Path ${env:PROGRAMFILES(X86)} -ChildPath 'Inno Setup 6\\ISCC.exe') $(Join-Path -Path $(Get-Location) -ChildPath "script.iss")
      
      - name: uploading artifact
        uses: actions/upload-artifact@v4
        with:
          name: uxplay-windows
          path: Output\uxplay-windows.exe
